name: "Publish to GitHub Pages"

env:
  GODOT_VERSION: 3.5.3
  PROJECT_PATH: src
  RELEASE_NAME: stable
  SUBDIR:
  GODOT_PLATFORM: linux_headless.64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Godot
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ca-certificates git git-lfs unzip wget zip rsync
          sudo wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}${SUBDIR}/Godot_v${GODOT_VERSION}-${RELEASE_NAME}_${GODOT_PLATFORM}.zip
          sudo wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}${SUBDIR}/Godot_v${GODOT_VERSION}-${RELEASE_NAME}_export_templates.tpz
          sudo mkdir ~/.cache
          sudo mkdir -p ~/.config/godot
          sudo mkdir -p ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME}
          sudo ln -s ~/.local/share/godot/templates ~/.local/share/godot/export_templates
          sudo unzip Godot_v${GODOT_VERSION}-${RELEASE_NAME}_${GODOT_PLATFORM}.zip
          sudo mv -v Godot_v${GODOT_VERSION}-${RELEASE_NAME}_${GODOT_PLATFORM} /usr/local/bin/godot
          sudo unzip Godot_v${GODOT_VERSION}-${RELEASE_NAME}_export_templates.tpz
          sudo mkdir -p /root/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME}
          sudo mv -v templates/* /root/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME}
          sudo rm -f Godot_v${GODOT_VERSION}-${RELEASE_NAME}_export_templates.tpz Godot_v${GODOT_VERSION}-${RELEASE_NAME}_${GODOT_PLATFORM}.zip
      - name: Build
        run: |
          sudo mkdir -v -p build/web
          cd $PROJECT_PATH
          sudo godot --export "HTML5" ../build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync
      - name: Deploy!
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: deploy
          folder: build/web
